#配置fast的路径
file.host=http://192.168.32.27:8888/
#配置oss外网上传的url
file.endpoint=https://oss-cn-hangzhou.aliyuncs.com
#配置oss用户的key
file.accessKeyId=yourAccessKeyId
#配置oss用户的secret
file.accessKeySecret=yourAccessKeySecret
#配置oss上传的分盘，类似于d盘
file.bucketName=examplebucket
#配置oss文件上传的路径，类似于文件夹
file.objectName=exampledir/exampleobject.txt
#外网想要直接读取的url
file.ossHost=https://imooctest.oss-cn-hangzhou.aliyuncs.com
