#server:
#  port: 9400
spring:
  datasource:                                           # 数据源的相关配置
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
#  redis:
#    #   单机模式
#    database: 1
#    password: imooc
#    host: 192.168.32.97